### ISSUE TITLE
Entity Type

### ISSUE THREAD

**Issue by Amit688** [likethecolor/Alchemy-API#12]
Hey,
Alchemy API is allowing to extract entity's type. I couldn't find it on your great client.
Can you add it please?

Example:
![image](https://cloud.githubusercontent.com/assets/6896734/5328551/bc70354e-7d8c-11e4-9298-c5a4c5821fd7.png)

Thanks!

**Comment by likethecolor** [comment]
I'm so sorry for the long delay in my reply.  An example can be found in the README.md and the source code `com.likethecolor.alchemy.Main`  It's the very last one.

Here's an example:

    final NamedEntityParams namedEntityParams = new NamedEntityParams();
    namedEntityParams.setIsCoreference(true);
    namedEntityParams.setIsDisambiguate(true);
    namedEntityParams.setIsLinkedData(true);
    namedEntityParams.setIsQuotations(true);
    namedEntityParams.setIsSentiment(true);
    namedEntityParams.setIsShowSourceText(true);

    AbstractCall<NamedEntityAlchemyEntity> rankedNamedEntitiesCall = new RankedNamedEntitiesCall(new CallTypeUrl("http://www.politico.com/blogs/media/2012/02/detroit-news-ed-upset-over-romney-edit-115247.html"), namedEntityParams);
    Response<NamedEntityAlchemyEntity> rankedNamedEntitiesResponse = client.call(rankedNamedEntitiesCall);
		Iterator<NamedEntityAlchemyEntity> iter = rankedNamedEntitiesResponse.iterator();
		while(iter.hasNext()) {
			NamedEntityAlchemyEntity e = iter.next();
			System.out.println(e.getText());
		}

Output

    Romney
    Nolan Finley
    Grand Rapids Press
    Detroit News
    Jim Romenesko
    editor
    press secretary
    editorial board
    automobile industry
    Andrea Saul
    The Press
