### ISSUE TITLE
how to implement http://www.alchemyapi.com/products/demo/alchemylanguage , just passing text

### ISSUE THREAD

**Issue by armdev** [likethecolor/Alchemy-API#14]
Hi,
How we can use Alchemy-API with just passing text, not a url, as in example
http://www.alchemyapi.com/products/demo/alchemylanguage
Just post text and get json/object.

Thanks

**Comment by Khalian** [comment]
I was able to do it by using CallTypeText

final AbstractCall<SentimentAlchemyEntity> sentimentCall = new SentimentCall(new CallTypeText("baba black sheep have you any wool"));
        System.out.println(alchemyClient.call(sentimentCall).toString(ToStringStyle.MULTI_LINE_STYLE));
