### ISSUE TITLE
Image from local drive not working

### ISSUE THREAD

**Issue by hemant4524** [likethecolor/Alchemy-API#15]
I put image in my source folder 

  byte[] imageByteArray = readFile("nike.jpg");

        AlchemyAPI_ImageParams imageParams = new AlchemyAPI_ImageParams();
        imageParams.setImage(imageByteArray);
        imageParams.setImagePostMode(AlchemyAPI_ImageParams.RAW);
        doc = alchemyObj.ImageGetRankedImageKeywords(imageParams);
        System.out.println(getStringFromDocument(doc));

Output:
post url:http://access.alchemyapi.com/calls/image/ImageGetRankedImageKeywords?apikey=1acef4430bcca2c57ede703893d4cede963c9890&outputMode=xml&imagePostMode=raw
<?xml version="1.0" encoding="UTF-8" standalone="no"?><results>
    <status>OK</status>
    <usage>By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html</usage>
    <url/>
    <totalTransactions>4</totalTransactions>
    <imageKeywords>
    </imageKeywords>
</results>

**Comment by likethecolor** [comment]
This doesn't look like this library.  There is no reference to AlchemyAPI_ImageParams in this library.
