### ISSUE TITLE
Update Library to Support HTTPS

### ISSUE THREAD

**Issue by gursev** [likethecolor/Alchemy-API#19]
The API does not support HTTPS. Consider adding it.

**Comment by gursev** [comment]
@likethecolor Can you please look into this request? Thank you!

**Comment by likethecolor** [comment]
I'll be glad to.

**Comment by gursev** [comment]
@likethecolor Thanks much :) Also, can you please add a security tag to it?

**Comment by likethecolor** [comment]
What is a security tag and how would I add it?

**Comment by likethecolor** [comment]
I've deployed and mastered version 1.2.1 which makes the call to AlchemyAPI using https and am closing this ticket.  If you can let me know more about a security tag I'll be glad to consider it.

**Comment by gursev** [comment]
@likethecolor Sorry I couldn't respond earlier. Thank you for the latest release. I will check it and revert.
