### ISSUE TITLE
alchemy unsupported-text-language

### ISSUE THREAD

**Issue by LucaMarzialetti** [likethecolor/Alchemy-API#22]
Dear @likethecolor ,
recently I encountered this problem using your alchemy-API for NER activities.
I've seen on the official release how to solve the problem, but actually I have no idea how to implement it in your code. [https://github.com/watson-developer-cloud/java-sdk/issues/204]
How to specify the language on alchemy-API?
Is possible to have a fix?
Thanks in advance :+1:

**Comment by likethecolor** [comment]
Sorry for the delay.  I just now received the email from github with this comment.  Let me do some investigation and get back to you.

**Comment by likethecolor** [comment]
I've made the change as version 1.3.1.  I have mastered the github code and released to the central repository (may take some time to get processed).  Thanks for your help and for using AlchemyAPI code.

`RelationParams params = new RelationParams();
  params.setLanguage(Language.ENGLISH);`

**Comment by LucaMarzialetti** [comment]
Dear Dan,
thanks for your fix :) i'm going to update maven repo and to add the mods.
Best regards :+1:
